xcopy /y "..\lib\hexml_10d.exp" "../../lib"
xcopy /y "..\lib\hexml_10d.ilk" "../../lib"
xcopy /y "..\lib\hexml_10d.dll" "../../lib"
xcopy /y "..\lib\hexml_10d.lib" "../../lib"
xcopy /y "..\lib\hexml_10d.dll" "../.."
xcopy /y "..\lib\hexml_10d.dll" "../dev"
